const particleStats = {
    dirt: {
        name: 'dirt',
        size: {min: 3, max: 10},
        colour: '#9d5100ff',
        lifetime: 500
    },
    timer: {
        name: 'timer',
        size: 15,
        colour: '#000',
        isTimer: true
    }
};

const aoeStats = {
    lumberjackRage: {
        name: 'lumberjackRage',
        radius: 3 * game.gridSize,
        damage: 179,
        lifetime: 5500,
        shrink: false,
        speedMult: 1.3,
        ctDamage: 54,
        rageDuration: 2000,
        colour: '#ff32f85d'
    },
    valkyrieAOE: {
        name: 'valkyrieAOE',
        radius: 60,
        damage: 266,
        target: 'ground'
    },
    iceSpiritAOE: {
        name: 'iceSpiritAOE',
        radius: 60,
        damage: 110,
        freezeDuration: 1200
    },
    fireSpiritAOE: {
        name: 'fireSpiritAOE',
        radius: 70,
        damage: 207
    },
    iceGolemDeathAOE: {
        name: 'iceGolemDeathAOE',
        radius: 60,
        damage: 84,
        slowDuration: 2000,
        slowAmount: 0.7
    },
    witchAOE: {
        name: 'witchAOE',
        radius: 45,
        damage: 335
    },
    golemDeathAOE: {
        name: 'golemDeathAOE',
        radius: 60,
        damage: 225
    },
    wallBreakerAOE: {
        name: 'wallBreakerAOE',
        radius: 45,
        damage: 391
    },
    megaKnightAttackAOE: {
        name: 'megaKnightAttackAOE',
        radius: 40,
        damage: 268,
        target: 'ground',
        id: 'attack'
    },
    megaKightJumpAOE: {
        name: 'megaKightJumpAOE',
        radius: 60,
        damage: 537,
        target: 'ground'
    },
    megaKnightSpawnAOE: {
        name: 'megaKnightSpawnAOE',
        radius: 66,
        damage: 430,
        lifetime: 500,
        target: 'ground'
    },
    balloonBombAOE: {
        name: 'balloonBombAOE',
        radius: 60,
        damage: 240
    },
    golemiteDeathAOE: {
        name: 'golemiteDeathAOE',
        radius: 60,
        damage: 99
    },
    skeletonDragonAOE: {
        name: 'skeletonDragonAOE',
        radius: 45,
        damage: 161
    },
    bombTowerBombAOE: {
        name: 'bombTowerBombAOE',
        radius: 72,
        damage: 222
    },
    bombTowerAOE: {
        name: 'bombTowerAOE',
        radius: 36,
        damage: 222
    },
    royalGhostAOE: {
        name: 'royalGhostAOE',
        radius: 26,
        damage: 261,
        target: 'ground'
    },
    princessAOE: {
        name: 'princessAOE',
        radius: 50,
        damage: 168
    },
    babyDragonAOE: {
        name: 'babyDragonAOE',
        radius: 36,
        damage: 161
    },
    darkPrinceAOE: {
        name: 'darkPrinceAOE',
        radius: 26,
        damage: 266,
        target: 'ground'
    },
    darkPrinceChargeAOE: {
        name: 'darkPrinceChargeAOE',
        radius: 26,
        damage: 532,
        target: 'ground'
    },
    bomberAOE: {
        name: 'bomberAOE',
        radius: 36,
        damage: 225
    },
    eWizardSpawnAOE: {
        name: 'eWizardSpawnAOE',
        radius: 72,
        damage: 192,
        stunDuration: 500
    },
    battleHealerSpawnAOE: {
        name: 'battleHealerSpawnAOE',
        radius: 60,
        damage: 0,
        heal: 202,
        colour: '#30b40071'
    },
    battleHealerAOE: {
        name: 'battleHealerAOE',
        radius: 96,
        damage: 0,
        heal: 102,
        colour: '#30b40071'
    },
    wizardAOE: {
        name: 'wizardAOE',
        radius: 36,
        damage: 281
    },
    mortarAOE: {
        name: 'mortarAOE',
        radius: 48,
        damage: 266,
        target: 'ground'
    },
    skeletonBarrelDeathAOE: {
        name: 'skeletonBarrelDeathAOE',
        radius: 48,
        damage: 145
    },
    eGiantAOE: {
        name: 'eGiantAOE',
        radius: 72,
        damage: 192,
        stunDuration: 500,
        ctDamage: 128
    },
    healSpiritAOE: {
        name: 'healSpiritAOE',
        radius: 36,
        damage: 110
    },
    healSpiritHealAOE: {
        name: 'healSpiritHealAOE',
        radius: 60,
        damage: 0,
        heal: 401,
        colour: '#30b40071'
    },
    iceWizardAOE: {
        name: 'iceWizardAOE',
        radius: 36,
        damage: 89,
        slowDuration: 2500,
        slowAmount: 0.7
    },
    iceWizardSpawnAOE: {
        name: 'iceWizardSpawnAOE',
        radius: 72,
        damage: 84,
        slowDuration: 1000,
        slowAmount: 0.7
    },
    royalDeliveryAOE: {
        name: 'royalDeliveryAOE',
        radius: 72,
        damage: 473
    },
    giantSkeletonBombAOE: {
        name: 'giantSkeletonBombAOE',
        radius: 72,
        damage: 535,
        ctDamage: 1068
    },
    sparkyAOE: {
        name: 'sparkyAOE',
        radius: 43.2,
        damage: 1331,
        target: 'ground'
    },
    goblinDemolisherAOE: {
        name: 'goblinDemolisherAOE',
        radius: 36,
        damage: 186
    },
    kamikazeGoblinAOE: {
        name: 'kamikazeGoblinAOE',
        radius: 60,
        damage: 404
    },
    phoenixDeathAOE: {
        name: 'phoenixDeathAOE',
        radius: 36,
        damage: 163
    },
    goblinDrillSpawnAOE: {
        name: 'goblinDrillSpawnAOE',
        radius: 60,
        damage: 84,
        ctDamage: 26
    }
};

const projectileStats = {
    princessTowerArrow: {
        name: 'princessTowerArrow',
        damage: 109,
        speed: 1000
    },
    kingTowerBullet: {
        name: 'kingTowerBullet',
        damage: 109,
        speed: 1000
    },
    archerArrow: {
        name: 'archerArrow',
        damage: 112,
        speed: 600
    },
    fireSpirit: {
        name: 'fireSpirit',
        size: 15,
        aoeStats: aoeStats.fireSpiritAOE,
        colour: '#ff9100ff',
        distance: 90,
        aoeOnDeath: true,
        groundProj: true
    },
    iceSpirit: {
        name: 'iceSpirit',
        size: 15,
        aoeStats: aoeStats.iceSpiritAOE,
        colour: '#00fafeff',
        distance: 90,
        aoeOnDeath: true,
        groundProj: true
    },
    dartGoblinDart: {
        name: 'dartGoblinDart',
        damage: 156,
        speed: 800
    },
    cannonBullet: {
        name: 'cannonBullet',
        damage: 212,
        speed: 1000
    },
    minionBullet: {
        name: 'minionBullet',
        damage: 107,
        speed: 1000,
        size: 3
    },
    megaMinionBullet: {
        name: 'megaMinionBullet',
        damage: 312,
        speed: 1000
    },
    lavaHoundBullet: {
        name: 'lavaHoundBullet',
        damage: 53,
        speed: 400,
        colour: '#ab08089e'
    },
    lavaPupBullet: {
        name: 'lavaPupBullet',
        damage: 81,
        colour: '#ab08089e'
    },
    witchBullet: {
        name: 'witchBullet',
        aoeStats: aoeStats.witchAOE,
        colour: '#7700aaff',
        size: 8,
        speed: 600
    },
    royalGiantBullet: {
        name: 'royalGiantBullet',
        damage: 307,
        size: 10,
        speed: 1000
    },
    mArcherArrow: {
        name: 'mArcherArrow',
        damage: 133,
        pierce: 9999,
        distance: 250,
        colour: '#00eaffff',
        targetPriority: 'all',
        size: 7,
        speed: 1000
    },
    bowlerBall: {
        name: 'bowlerBall',
        damage: 289,
        size: 23,
        pierce: 9999,
        distance: 180,
        speed: 170,
        colour: '#919191ff',
        targetPriority: 'ground',
        knockback: 3
    },
    musketeerBullet: {
        name: 'musketeerBullet',
        damage: 217,
        speed: 1000
    },
    skeletonDragonFireBall: {
        name: 'skeletonDragonFireBall',
        aoeStats: aoeStats.skeletonDragonAOE,
        colour: '#ff8400ff',
        size: 8,
        aoeOnDeath: true,
        groundProj: true
    },
    spearGoblinSpear: {
        name: 'spearGoblinSpear',
        damage: 81
    },
    eSpiritLightning: {
        name: 'eSpiritLightning',
        damage: 99,
        type: 'lightning',
        stunDuration: 500,
        chainAmount: 9,
        range: 4 * game.gridSize
    },
    eDragonLightning: {
        name: 'eDragonLightning',
        damage: 192,
        type: 'lightning',
        stunDuration: 500,
        chainAmount: 3,
        range: 70
    },
    xBowBullet: {
        name: 'xBowBullet',
        damage: 43,
        speed: 1400,
        size: 4,
        distance: 300
    },
    bombTowerBullet: {
        name: 'bombTowerBullet',
        aoeStats: aoeStats.bombTowerAOE,
        size: 10,
        aoeOnDeath: true,
        groundProj: true
    },
    princessArrows: {
        name: 'princessArrows',
        aoeStats: aoeStats.princessAOE,
        distance: 250,
        aoeOnDeath: true,
        groundProj: true,
        speed: 600
    },
    babyDragonFire: {
        name: 'babyDragonFire',
        colour: '#ff8800da',
        aoeStats: aoeStats.babyDragonAOE,
        size: 10,
        aoeOnDeath: true,
        groundProj: true
    },
    bomberBomb: {
        name: 'bomberBomb',
        aoeStats: aoeStats.bomberAOE,
        speed: 400,
        size: 10,
        aoeOnDeath: true,
        groundProj: true
    },
    eWizardLightning: {
        name: 'eWizardLightning',
        damage: 230,
        type: 'lightning',
        stunDuration: 500,
        chainAmount: 1,
        range: 1,
        coolDown: 250
    },
    motherWitchBullet: {
        name: 'motherWitchBullet',
        damage: 133,
        speed: 600,
        pigCurseDuration: 5000,
        colour: '#bf00ffff'
    },
    wizardFireball: {
        name: 'wizardFireball',
        aoeStats: aoeStats.wizardAOE,
        colour: '#ff8800da',
        size: 10,
        speed: 600
    },
    mortarRock: {
        name: 'mortarRock',
        aoeStats: aoeStats.mortarAOE,
        colour: '#a0a0a0',
        size: 13,
        speed: 300,
        distance: 300,
        aoeOnDeath: true,
        groundProj: true
    },
    teslaLightning: {
        name: 'teslaLightning',
        damage: 220,
        type: 'lightning',
        chainAmount: 1,
        range: 1,
        coolDown: 250
    },
    healSpirit: {
        name: 'healSpirit',
        size: 15,
        aoeStats: aoeStats.healSpiritAOE,
        aoeStats2: aoeStats.healSpiritHealAOE,
        colour: '#ffdd00e2',
        distance: 90,
        aoeOnDeath: true,
        groundProj: true
    },
    iceWizardBullet: {
        name: 'iceWizardBullet',
        aoeStats: aoeStats.iceWizardAOE,
        colour: '#00fbffa6',
        size: 8,
        speed: 700
    },
    firecrackerBullet: {
        name: 'firecrackerBullet',
        damage: 64,
        size: 10,
        distance: 144,
        colour: '#ff00f2ff',
        speed: 550,
        splitNumber: 5,
        splitSpread: Math.PI / 4,
        splitStats: null,
        groundProj: true
    },
    firecrackerSplit: {
        name: 'firecrackerSplit',
        damage: 64,
        size: 8,
        distance: 120,
        colour: '#7e4100ff',
        pierce: 9999,
        targetPriority: 'all',
        speed: 550
    },
    eGiantZap: {
        name: 'eGiantZap',
        damage: 192,
        stunDuration: 500,
        type: 'lightning',
        ctDamage: 128,
        chainAmount: 1,
        range: 1,
        coolDown: 200
    },
    flyingMachineBullet: {
        name: 'flyingMachineBullet',
        damage: 171,
        speed: 800
    },
    zappiesZap: {
        name: 'zappiesZap',
        damage: 117,
        stunDuration: 500,
        type: 'lightning',
        chainAmount: 1,
        range: 1
    },
    furncaceBullet: {
        name: 'furncaceBullet',
        damage: 179,
        colour: '#ff8800da'
    },
    rascalSling: {
        name: 'rascalSling',
        damage: 125,
        speed: 800
    },
    sparkyBullet: {
        name: 'sparkyBullet',
        aoeStats: aoeStats.sparkyAOE,
        size: 15,
        colour: '#00e5ffda',
        speed: 1400
    },
    goblinDemolisherBomb: {
        name: 'goblinDemolisherBomb',
        aoeStats: aoeStats.goblinDemolisherAOE,
        speed: 400,
        size: 8,
        colour: '#b80000d0',
        aoeOnDeath: true,
        groundProj: true
    },
    cannonCartBullet: {
        name: 'cannonCartBullet',
        damage: 212,
        speed: 1000
    },
    executionerAxe: {
        name: 'executionerAxe',
        damage: 168,
        colour: '#676767ff',
        size: game.gridSize,
        distance: 180,
        returns: true,
        speed: 550,
        pierce: 9999,
        targetPriority: 'all'
    },
    hunterBullet: {
        name: 'hunterBullet',
        damage: 84,
        speed: 550,
        distance: 156,
        targetPriority: 'all'
    },
    ramRiderSnare: {
        name: 'ramRiderSnare',
        damage: 104,
        speed: 600,
        snareDuration: 2000
    },
    fishermanHook: {
        name: 'fishermanHook',
        damage: 0,
        speed: 800,
        slowAmount: 0.7,
        slowDuration: 1500
    }
};

projectileStats.firecrackerBullet.splitStats = projectileStats.firecrackerSplit;

const otherUnits = {
    golemite: {
        name: 'Golem',
        symbol: '🗿',
        imgPath: '../Imgs/Sprites/Golemite.png',
        hp: 1039,
        damage: 84,
        deathAOEStats: aoeStats.golemiteDeathAOE,
        attackSpeed: 2500,
        initHitSpeed: 1000,
        range: 21,
        viewRange: 7 * game.gridSize,
        size: 20,
        speed: 45,
        targetPriority: 'buildings',
        type: 'unit'
    },
    lavaPup: {
        name: 'Lava Pup',
        symbol: '🐦‍🔥',
        hp: 217,
        projectileStats: projectileStats.lavaPupBullet,
        attackSpeed: 1300,
        initHitSpeed: 1000,
        range: 38.4,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 60,
        targetPriority: 'all',
        type: 'flying'
    },
    skeleton: {
        name: 'Skeleton',
        symbol: '💀',
        imgPath: '../Imgs/Sprites/Skeleton.png',
        hp: 81,
        damage: 81,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 0.53 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        targetPriority: 'ground',
        type: 'unit'
    },
    balloonBomb: {
        name: 'Balloon Bomb',
        symbol: '💣',
        hp: 3000,
        deathAOEStats: aoeStats.balloonBombAOE,
        attackSpeed: 2000,
        range: 20,
        viewRange: 7.7 * game.gridSize,
        size: 15,
        speed: 0,
        targetPriority: 'ground',
        type: 'bomb',
        hpLostPerSecond: 400 * 4
    },
    diddy: {
        name: 'Diddy',
        symbol: '🐸',
        hp: 1080,
        damage: 337,
        attackSpeed: 1100,
        initHitSpeed: 200,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 90,
        targetPriority: 'ground',
        type: 'unit'
    },
    bombTowerBomb: {
        name: 'Bomb Tower Bomb',
        symbol: '💣',
        hp: 3000,
        deathAOEStats: aoeStats.bombTowerBombAOE,
        attackSpeed: 2000,
        range: 20,
        viewRange: 15,
        size: 15,
        speed: 0,
        targetPriority: 'ground',
        type: 'bomb',
        hpLostPerSecond: 400 * 4
    },
    barbarian: {
        name: 'Barbarian',
        symbol: '😡',
        hp: 670,
        damage: 192,
        attackSpeed: 1300,
        initHitSpeed: 400,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        targetPriority: 'ground',
        type: 'unit'
    },
    cursedPig: {
        name: 'Cursed Pig',
        symbol: '🐷',
        hp: 629,
        damage: 53,
        attackSpeed: 1200,
        initHitSpeed: 250,
        range: 24,
        viewRange: 9.5 * game.gridSize,
        size: 16,
        speed: 120,
        targetPriority: 'buildings',
        type: 'unit'
    },
    bushGoblin: {
        name: 'Bush Goblin',
        symbol: '🌲',
        hp: 304,
        damage: 256,
        attackSpeed: 1400,
        range: 0.8 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    goblin: {
        name: 'Goblin',
        symbol: '🤢',
        hp: 202,
        damage: 120,
        attackSpeed: 1100,
        initHitSpeed: 600,
        range: 16,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 120,
        targetPriority: 'ground',
        type: 'spell'
    },
    fireSpirit: {
        name: 'Fire Spirit',
        symbol: '🔥',
        hp: 230,
        projectileStats: projectileStats.fireSpirit,
        attackSpeed: 2000,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        targetPriority: 'all',
        type: 'unit',
        dieOnAttack: true
    },
    bat: {
        name: 'Bat',
        symbol: '🦇',
        hp: 81,
        damage: 81,
        attackSpeed: 1300,
        initHitSpeed: 600,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        targetPriority: 'all',
        type: 'flying'
    },
    spearGoblin: {
        name: 'Spear Goblin',
        symbol: '👺',
        hp: 133,
        projectileStats: projectileStats.spearGoblinSpear,
        attackSpeed: 1700,
        initHitSpeed: 500,
        range: 120,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 120,
        targetPriority: 'all',
        type: 'unit'
    },
    rascalBoy: {
        name: 'Rascal Boy',
        symbol: '👨🏻',
        imgPath: '../Imgs/Sprites/Rascal_Boy.png',
        hp: 1940,
        damage: 204,
        attackSpeed: 1500,
        initHitSpeed: 400,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    rascalGirl: {
        name: 'Rascal Girl',
        symbol: '👩🏻',
        imgPath: '../Imgs/Sprites/Rascal_Girl.png',
        hp: 261,
        projectileStats: projectileStats.rascalSling,
        attackSpeed: 1000,
        initHitSpeed: 500,
        range: 120,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    elixirGolemite: {
        name: 'Elixir Golemite',
        symbol: 'O',
        imgPath: '../Imgs/Sprites/Elixir_Golemite.png',
        hp: 762,
        damage: 128,
        deathSpawnNum: 2,
        deathSpawnStats: null,
        attackSpeed: 1100,
        initHitSpeed: 800,
        range: 30,
        viewRange: 7.5 * game.gridSize,
        size: 18,
        speed: 60,
        targetPriority: 'buildings',
        type: 'unit',
        deathEnemyElixir: 0.5
    },
    elixirBlob: {
        name: 'Elixir Blob',
        symbol: 'o',
        imgPath: '../Imgs/Sprites/Elixir_Blob.png',
        hp: 360,
        damage: 64,
        attackSpeed: 1100,
        initHitSpeed: 800,
        range: 25,
        viewRange: 7.5 * game.gridSize,
        size: 16,
        speed: 90,
        targetPriority: 'buildings',
        type: 'unit',
        deathEnemyElixir: 0.5
    },
    giantSkeletonBomb: {
        name: 'Giant Skeleton Bomb',
        symbol: '💣',
        hp: 3000,
        deathAOEStats: aoeStats.giantSkeletonBombAOE,
        attackSpeed: 2000,
        range: 20,
        viewRange: 15,
        size: 15,
        speed: 0,
        targetPriority: 'ground',
        type: 'bomb',
        hpLostPerSecond: 400 * 4
    },
    kamikazeGoblin: {
        name: 'Goblin Demolisher',
        symbol: '💥',
        hp: 1300,
        damage: 0,
        deathAOEStats: aoeStats.kamikazeGoblinAOE,
        attackSpeed: 2000,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 120,
        targetPriority: 'buildings',
        type: 'unit',
        hpLostPerSecond: 65,
        dieOnAttack: true
    },
    brokenCannonCart: {
        name: 'Cannon Cart',
        symbol: '🛒',
        hp: 1809,
        projectileStats: projectileStats.cannonCartBullet,
        attackSpeed: 900,
        initHitSpeed: 500,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 0,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 30.15
    },
    phoenixEgg: {
        name: 'Phoenix Egg',
        symbol: '🥚',
        hp: 240,
        attackSpeed: 2000,
        range: 20,
        viewRange: 15,
        size: 15,
        speed: 0,
        targetPriority: 'ground',
        type: 'building',
        supportSpawnSpeed: 4300,
        supportStats: null,
        supportSpawnNum: 1,
        dieOnSupportSpawn: true
    },
    babyPhoenix: {
        name: 'Baby Phoenix',
        symbol: '🐦‍🔥',
        hp: 1052 * 0.8,
        damage: 217 * 0.8,
        attackSpeed: 1000,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    miner: {
        name: 'Miner',
        symbol: '🪏',
        hp: 1210,
        damage: 194,
        attackSpeed: 1300,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 19,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'spell'
    },
    goblinDrill: {
        name: 'Goblin Drill',
        symbol: '🛠️',
        cost: 4,
        hp: 1313,
        attackSpeed: 1000,
        initHitSpeed: 1000,
        range: 132,
        viewRange: game.gridSize,
        size: game.gridSize,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'building',
        deployType: 'spell',
        hpLostPerSecond: 131.3,
        spawnAOEStats: aoeStats.goblinDrillSpawnAOE,
        supportSpawnSpeed: 3000,
        initSupportSpawnSpeed: 800,
        supportStats: null,
        supportSpawnNum: 1,
        deathSpawnNum: 2,
        deathSpawnStats: null
    },
    ramRider: {
        name: 'Ram Rider',
        symbol: '👩‍🦲',
        hp: 9999,
        projectileStats: projectileStats.ramRiderSnare,
        attackSpeed: 1100,
        initHitSpeed: 400,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        targetPriority: 'units',
        type: 'unit'
    }
};

otherUnits.elixirGolemite.deathSpawnStats = otherUnits.elixirBlob;
otherUnits.phoenixEgg.supportStats = otherUnits.babyPhoenix;
otherUnits.goblinDrill.supportStats = otherUnits.goblin;
otherUnits.goblinDrill.deathSpawnStats = otherUnits.goblin;

const units = {
    knight: {
        name: 'Knight',
        symbol: '⚔️',
        imgPath: '../Imgs/Sprites/Knight.png',
        cost: 3,
        hp: 1766,
        damage: 202,
        attackSpeed: 1200,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
    },
    archers: {
        name: 'Archers',
        symbol: '🏹',
        imgPath: '../Imgs/Sprites/Archer.png',
        cost: 3,
        hp: 304,
        projectileStats: projectileStats.archerArrow,
        attackSpeed: 900,
        initHitSpeed: 500,
        range: 5 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        count: 2,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    giant: {
        name: 'Giant',
        symbol: '💪',
        imgPath: '../Imgs/Sprites/Giant.png',
        cost: 5,
        hp: 4090,
        damage: 253,
        attackSpeed: 1500,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings', 
        type: 'unit'
    },
    skeletons: {
        name: 'Skeletons',
        symbol: '💀',
        imgPath: '../Imgs/Sprites/Skeleton.png',
        cost: 1,
        hp: 81,
        damage: 81,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 0.53 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        count: 3,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    skarmy: {
        name: 'Skeleton Army',
        symbol: '💀',
        displaySymbol: '💀💀',
        imgPath: '../Imgs/Sprites/Skeleton.png',
        cost: 3,
        hp: 81,
        damage: 81,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 0.53 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        count: 15,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    fireball: {
        name: 'Fireball',
        symbol: '☄️',
        imgPath: '../Imgs/Sprites/Fireball.png',
        cost: 4,
        type: 'spell',
        radius: 2.5 * game.gridSize,
        damage: 688,
        ctDamage: 207,
        knockback: 4
    },
    arrows: {
        name: 'Arrows',
        symbol: '🎯',
        imgPath: '../Imgs/Sprites/Arrows.png',
        cost: 3,
        type: 'spell',
        radius: 5 * game.gridSize,
        damage: 122,
        lifetime: 500,
        ctDamage: 31,
        pulseTime: 200,
        pulseCount: 3
    },
    rage: {
        name: 'Rage',
        symbol: '🟣',
        imgPath: '../Imgs/Sprites/Rage.png',
        cost: 2,
        type: 'spell',
        radius: 3 * game.gridSize,
        damage: 179,
        lifetime: 4500,
        shrink: false,
        speedMult: 1.3,
        rageDuration: 2000,
        ctDamage: 54,
        colour: '#ff32f85d'
    },
    zap: {
        name: 'Zap',
        symbol: '🌩️',
        imgPath: '../Imgs/Sprites/Zap.png',
        cost: 2,
        type: 'spell',
        radius: 2.5 * game.gridSize,
        damage: 192,
        lifetime: 500,
        stunDuration: 500,
        ctDamage: 58
    },
    rocket: {
        name: 'Rocket',
        symbol: '🚀',
        imgPath: '../Imgs/Sprites/Rocket.png',
        cost: 6,
        type: 'spell',
        radius: 2 * game.gridSize,
        damage: 1484,
        ctDamage: 371
    },
    snowball: {
        name: 'Giant Snowball',
        symbol: '❅',
        imgPath: '../Imgs/Sprites/Giant_Snowball.png',
        cost: 2,
        type: 'spell',
        radius: 2.5 * game.gridSize,
        damage: 179,
        slowDuration: 3000,
        slowAmount: 0.7,
        ctDamage: 54,
        knockback: 4
    },
    poison: {
        name: 'Poison',
        symbol: '🔴',
        imgPath: '../Imgs/Sprites/Poison.png',
        cost: 4,
        type: 'spell',
        radius: 3.5 * game.gridSize,
        damage: 92,
        moveSpeedMult: 0.85,
        lifetime: 8000,
        ctDamage: 23,
        pulseTime: 1000,
        pulseCount: 8,
        shrink: false,
        colour: '#7b000086'
    },
    earthquake: {
        name: 'Earthquake',
        symbol: '🟤',
        imgPath: '../Imgs/Sprites/Earthquake.png',
        cost: 3,
        type: 'spell',
        radius: 3.5 * game.gridSize,
        damage: 84,
        moveSpeedMult: 0.5,
        lifetime: 1000,
        buidlingDamage: 287,
        ctDamage: 53,
        pulseTime: 1000,
        pulseCount: 3,
        shrink: false,
        colour: '#7b000086',
        target: 'ground'
    },
    tornado: {
        name: 'Tornado',
        symbol: '🌪️',
        imgPath: '../Imgs/Sprites/Tornado.png',
        cost: 3,
        type: 'spell',
        radius: 5.5 * game.gridSize,
        damage: 42,
        lifetime: 1050,
        ctDamage: 29,
        pulseTime: 550,
        pulseCount: 2,
        pullForce: 0.5,
        shrink: false,
        colour: '#b0b0b05d',
        target: 'ground'
    },
    vines: {
        name: 'Vines',
        symbol: '🥀',
        imgPath: '../Imgs/Sprites/Vines.png',
        cost: 3,
        type: 'spell',
        radius: 2.5 * game.gridSize,
        damage: 153,
        ctDamage: 38,
        hitCount: 3,
        pulseCount: 2,
        pulseTime: 1000,
        vineDuration: 2500,
        colour: '#186d0097'
    },
    goblinCurse: {
        name: 'Goblin Curse',
        symbol: '🍾',
        imgPath: '../Imgs/Sprites/Goblin_Curse.png',
        cost: 2,
        type: 'spell',
        radius: 3 * game.gridSize,
        damage: 30,
        ctDamage: 6,
        pulseCount: 6,
        pulseTime: 1000,
        goblinCurse: true,
        shrink: false,
        colour: '#1efd0066'
    },
    freeze: {
        name: 'Freeze',
        symbol: '🧊',
        imgPath: '../Imgs/Sprites/Freeze.png',
        cost: 4,
        type: 'spell',
        radius: 3 * game.gridSize,
        damage: 115,
        lifetime: 4000,
        freezeDuration: 4000,
        shrink: false,
        canHitHidden: true,
        colour: '#00c8ffc5'
    },
    clone: {
        name: 'Clone',
        symbol: '🧬',
        imgPath: '../Imgs/Sprites/Clone.png',
        cost: 3,
        type: 'spell',
        radius: 3 * game.gridSize,
        damage: 0,
        clone: true
    },
    graveyard: {
        name: 'Graveyard',
        symbol: '🪦🪦',
        imgPath: '../Imgs/Sprites/Graveyard.png',
        cost: 5,
        type: 'spell',
        radius: 4 * game.gridSize,
        damage: 0,
        lifetime: 9000,
        spawnSpeed: 500,
        initSpawnSpeed: 2200,
        spawnStats: otherUnits.skeleton,
        shrink: false,
        colour: '#70009294'
    },
    void: {
        name: 'Void',
        symbol: '🕳️',
        imgPath: '../Imgs/Sprites/Void.png',
        cost: 3,
        type: 'spell',
        radius: 2.5 * game.gridSize,
        damage: [340, 160, 76],
        ctDamage: [48, 25, 17],
        pulseTime: 1000,
        pulseCount: 3,
        lifetime: 4000,
        shrink: false
    },
    lighting: {
        name: 'Lightning',
        symbol: '⚡️⚡️',
        imgPath: '../Imgs/Sprites/Lightning.png',
        cost: 6,
        type: 'spell',
        radius: 3.5 * game.gridSize,
        damage: 1057,
        ctDamage: 286,
        hitCount: 3,
        stunDuration: 500
    },
    valkyrie: {
        name: 'Valkyrie',
        symbol: '🛡️',
        imgPath: '../Imgs/Sprites/Valkyrie.png',
        cost: 4,
        hp: 1907,
        attackSpeed: 1500,
        initHitSpeed: 100,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        aoeStats: aoeStats.valkyrieAOE
    },
    hogRider: {
        name: 'Hog Rider',
        symbol: '🐗',
        cost: 4,
        hp: 1697,
        damage: 317,
        attackSpeed: 1600,
        initHitSpeed: 600,
        range: 21,
        viewRange: 9.5 * game.gridSize,
        size: 20,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit'
    },
    miniPekka: {
        name: 'Mini Pekka',
        symbol: '🤖',
        imgPath: '../Imgs/Sprites/Mini_Pekka.png',
        cost: 4,
        hp: 1433,
        damage: 755,
        attackSpeed: 1600,
        initHitSpeed: 500,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    iceGolem: {
        name: 'Ice Golem',
        symbol: '⛄',
        cost: 2,
        hp: 1198,
        damage: 84,
        deathAOEStats: aoeStats.iceGolemDeathAOE,
        slowDuration: 2000,
        slowAmount: 0.7,
        attackSpeed: 2500,
        initHitSpeed: 1000,
        range: 21,
        viewRange: 7 * game.gridSize,
        size: 20,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit'
    },
    goblinBarrel: {
        name: 'Goblin Barrel',
        symbol: '🤢',
        imgPath: '../Imgs/Sprites/Goblin_Barrel.png',
        cost: 3,
        type: 'spell',
        damage: 0,
        distance: 9999,
        size: 20,
        speed: 200,
        colour: '#b16800ff',
        lifetime: 9999,
        deathSpawnStats: otherUnits.goblin,
        deathSpawnNum: 3
    },
    fireSpirit: {
        name: 'Fire Spirit',
        symbol: '🔥',
        imgPath: '../Imgs/Sprites/Fire_Spirit.png',
        cost: 1,
        hp: 230,
        projectileStats: projectileStats.fireSpirit,
        attackSpeed: 2000,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        dieOnAttack: true
    },
    pekka: {
        name: 'Pekka',
        symbol: '🦾',
        imgPath: '../Imgs/Sprites/Pekka.png',
        cost: 7,
        hp: 3760,
        damage: 816,
        attackSpeed: 1800,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    dartGoblin: {
        name: 'Dart Goblin',
        symbol: '👹',
        imgPath: '../Imgs/Sprites/Dart_Goblin.png',
        cost: 3,
        hp: 261,
        projectileStats: projectileStats.dartGoblinDart,
        attackSpeed: 800,
        initHitSpeed: 350,
        range: 156,
        viewRange: 7.5 * game.gridSize,
        size: 18,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    cannon: {
        name: 'Cannon',
        symbol: '💣',
        cost: 3,
        hp: 824,
        projectileStats: projectileStats.cannonBullet,
        attackSpeed: 1000,
        initHitSpeed: 1000,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 27.4
    },
    minions: {
        name: 'Minions',
        symbol: '😈',
        imgPath: '../Imgs/Sprites/Minion.png',
        cost: 3,
        hp: 230,
        projectileStats: projectileStats.minionBullet,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        count: 3,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    minionHorde: {
        name: 'Minion Horde',
        symbol: '😈',
        displaySymbol: '😈😈',
        imgPath: '../Imgs/Sprites/Minion.png',
        cost: 5,
        hp: 230,
        projectileStats: projectileStats.minionBullet,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        count: 6,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    megaMinion: {
        name: 'Mega Minion',
        symbol: '👿',
        imgPath: '../Imgs/Sprites/Mega_Minion.png',
        cost: 3,
        hp: 837,
        projectileStats: projectileStats.megaMinionBullet,
        attackSpeed: 1100,
        initHitSpeed: 400,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    golem: {
        name: 'Golem',
        symbol: '🗿',
        imgPath: '../Imgs/Sprites/Golem.png',
        cost: 8,
        hp: 5120,
        damage: 312,
        deathAOEStats: aoeStats.golemDeathAOE,
        deathSpawnNum: 2,
        deathSpawnStats: otherUnits.golemite,
        attackSpeed: 2500,
        initHitSpeed: 1000,
        range: 25,
        viewRange: 7 * game.gridSize,
        size: 23,
        speed: 45,
        deployTime: 3000,
        targetPriority: 'buildings',
        type: 'unit'
    },
    wallBreakers: {
        name: 'Wall Breakers',
        symbol: '🧨',
        imgPath: '../Imgs/Sprites/Wall_Breakers.png',
        cost: 2,
        hp: 330,
        damage: 391,
        attackSpeed: 2500,
        range: 13,
        viewRange: 7 * game.gridSize,
        size: 12,
        speed: 120,
        count: 2,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        aoeStats: aoeStats.wallBreakerAOE
    },
    lavaHound: {
        name: 'Lava Hound',
        symbol: '🐦‍🔥',
        cost: 7,
        hp: 3581,
        projectileStats: projectileStats.lavaHoundBullet,
        deathSpawnNum: 6,
        deathSpawnStats: otherUnits.lavaPup,
        attackSpeed: 1300,
        initHitSpeed: 1000,
        range: 3.5 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'flying'
    },
    iceSpirit: {
        name: 'Ice Spirit',
        symbol: '❄️',
        imgPath: '../Imgs/Sprites/Ice_Spirit.png',
        cost: 1,
        hp: 230,
        projectileStats: projectileStats.iceSpirit,
        attackSpeed: 2000,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        dieOnAttack: true
    },
    witch: {
        name: 'Witch',
        symbol: '🧛‍♀️',
        cost: 5,
        hp: 839,
        projectileStats: projectileStats.witchBullet,
        supportSpawnNum: 4,
        supportSpawnSpeed: 7000,
        initSupportSpawnSpeed: 1000,
        supportStats: otherUnits.skeleton,
        attackSpeed: 1100,
        initHitSpeed: 700,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    royalGiant: {
        name: 'Royal Giant', 
        symbol: '💣',
        cost: 6, 
        hp: 3164,
        projectileStats: projectileStats.royalGiantBullet,
        attackSpeed: 1700,
        initHitSpeed: 900,
        range: 120, 
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings', 
        type: 'unit'
    },
    bandit: {
        name: 'Bandit',
        symbol: '💰',
        cost: 3,
        hp: 906, 
        damage: 194,
        dashDamage: 389,
        dashRange: {min: 84, max: 144},
        dashSpeed: 600,
        dashPauseTime: 800,
        attackSpeed: 1000,
        initHitSpeed: 400,
        range: 23,
        viewRange: 6 * game.gridSize,
        size: 20,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    megaKnight: {
        name: 'Mega Knight',
        symbol: '⚙️',
        imgPath: '../Imgs/Sprites/Mega_Knight.png',
        cost: 7,
        hp: 3993, 
        dashRange: {min: 84, max: 120},
        dashSpeed: 240,
        dashAOEStats: aoeStats.megaKightJumpAOE,
        dashPauseTime: 900,
        attackSpeed: 1200,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 22,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        aoeStats: aoeStats.megaKnightAttackAOE,
        spawnAOEStats: aoeStats.megaKnightSpawnAOE
    },
    bats: {
        name: 'Bats',
        symbol: '🦇',
        cost: 2,
        hp: 81,
        damage: 81,
        attackSpeed: 1300,
        initHitSpeed: 600,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        count: 5,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    balloon: {
        name: 'Balloon',
        symbol: '🎈',
        cost: 5,
        hp: 1679,
        damage: 640,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.balloonBomb,
        attackSpeed: 2000,
        initHitSpeed: 200,
        range: 21,
        viewRange: 7.7 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'flying'
    },
    diddyCage: {
        name: 'Diddy Cage',
        symbol: '🎁',
        cost: 4,
        hp: 780,
        damage: 0,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.diddy,
        attackSpeed: 4000,
        range: game.gridSize * 1.1,
        viewRange: game.gridSize * 1.1,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'building',
        hpLostPerSecond: 39
    },
    lumberjack: {
        name: 'Lumberjack',
        symbol: '🪓',
        cost: 4,
        hp: 1282,
        damage: 256,
        deathAOEStats: aoeStats.lumberjackRage,
        attackSpeed: 800,
        initHitSpeed: 400,
        range: 30,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    prince: {
        name: 'Prince',
        symbol: '💈',
        cost: 5,
        hp: 1920,
        damage: 391,
        chargeDamage: 783,
        chargeSpeed: 120,
        chargeTriggerDistance: 48,
        attackSpeed: 1400,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    mArcher: {
        name: 'Magic Archer',
        symbol: '💠',
        cost: 4,
        hp: 529,
        projectileStats: projectileStats.mArcherArrow,
        attackSpeed: 1100,
        initHitSpeed: 700,
        range: 156,
        viewRange: 7.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    bowler: {
        name: 'Bowler',
        symbol: '🎳',
        cost: 5,
        hp: 2081,
        projectileStats: projectileStats.bowlerBall,
        attackSpeed: 2500,
        initHitSpeed: 500,
        range: 96,
        viewRange: 4 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    guards: {
        name: 'Guards',
        symbol: '☠️',
        cost: 3,
        hp: 81,
        sheildHP: 256,
        damage: 117,
        attackSpeed: 1000,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 90,
        count: 3,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    recruits: {
        name: 'Royal Recruits',
        symbol: '🪣',
        imgPath: '../Imgs/Sprites/Royal_Recruit.png',
        cost: 7,
        hp: 547,
        sheildHP: 240,
        damage: 133,
        attackSpeed: 1300,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 19,
        speed: 90,
        count: 6,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    barbarians: {
        name: 'Barbarians',
        symbol: '😡',
        cost: 5,
        hp: 670,
        damage: 192,
        attackSpeed: 1300,
        initHitSpeed: 400,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        count: 5,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    log: {
        name: 'Log',
        symbol: '🪵',
        imgPath: '../Imgs/Sprites/Log.png',
        cost: 2,
        type: 'unit',
        pierce: 9999,
        width: 3.9 * game.gridSize,
        height: 24,
        damage: 266,
        distance: 10.1 * game.gridSize,
        knockback: 4,
        targetPriority: 'ground',
        speed: 100,
        colour: '#b16800',
        lifetime: 9999,
        ctDamage: 40
    },
    musketeer: {
        name: 'Musketeer',
        symbol: '🔫',
        cost: 4,
        hp: 721,
        projectileStats: projectileStats.musketeerBullet,
        attackSpeed: 1000,
        initHitSpeed: 700,
        range: 140,
        viewRange: 6 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    eBarbarians: {
        name: 'Elite Barbarians',
        symbol: '🗡️',
        cost: 6,
        hp: 1341,
        damage: 384,
        attackSpeed: 1400,
        initHitSpeed: 500,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 90,
        count: 2,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    skeletonDragons: {
        name: 'Skeleton Dragons',
        symbol: '🦎',
        cost: 4,
        hp: 560,
        projectileStats: projectileStats.skeletonDragonFireBall,
        attackSpeed: 1900,
        initHitSpeed: 400,
        range: 84,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 120,
        count: 2,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    spearGoblins: {
        name: 'Spear Goblins',
        symbol: '👺',
        cost: 2,
        hp: 133,
        projectileStats: projectileStats.spearGoblinSpear,
        attackSpeed: 1700,
        initHitSpeed: 500,
        range: 120,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 120,
        count: 3,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    goblins: {
        name: 'Goblins',
        symbol: '🤢',
        cost: 2,
        hp: 202,
        damage: 120,
        attackSpeed: 1100,
        initHitSpeed: 600,
        range: 23,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 120,
        count: 4,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    eSpirit: {
        name: 'Electro Spirit',
        symbol: '⚡️',
        cost: 1,
        hp: 230,
        projectileStats: projectileStats.eSpiritLightning,
        attackSpeed: 2000,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        dieOnAttack: true
    },
    eDragon: {
        name: 'Electro Dragon',
        symbol: '🎸',
        cost: 5,
        hp: 949,
        projectileStats: projectileStats.eDragonLightning,
        attackSpeed: 2100,
        initHitSpeed: 700,
        range: 84,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    iDragon: {
        name: 'Inferno Dragon',
        symbol: '🐲',
        imgPath: '../Imgs/Sprites/Inferno_Dragon.png',
        cost: 4,
        hp: 1295,
        beamDamage: [35, 120, 422],
        damageStageTime: 2000,
        attackSpeed: 400,
        range: 84,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    xBow: {
        name: 'X-Bow',
        symbol: '💘',
        cost: 6,
        hp: 1600,
        projectileStats: projectileStats.xBowBullet,
        attackSpeed: 300,
        initHitSpeed: 300,
        range: 11.5 * game.gridSize,
        viewRange: 11.5 * game.gridSize,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 3500,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 27.4
    },
    infernoTower: {
        name: 'Inferno Tower',
        symbol: '💥',
        cost: 5,
        hp: 1748,
        beamDamage: [43, 158, 847],
        damageStageTime: 2000,
        attackSpeed: 400,
        range: 6 * game.gridSize,
        viewRange: 6 * game.gridSize,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'building',
        hpLostPerSecond: 58.3
    },
    bombTower: {
        name: 'Bomb Tower',
        symbol: '🧯',
        cost: 4,
        hp: 1356,
        projectileStats: projectileStats.bombTowerBullet,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.bombTowerBomb,
        attackSpeed: 1800,
        initHitSpeed: 500,
        range: 6 * game.gridSize,
        viewRange: 6 * game.gridSize,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'building',
        hpLostPerSecond: 45.2
    },
    royalGhost: {
        name: 'Royal Ghost',
        symbol: '👻',
        cost: 3,
        hp: 1210,
        aoeStats: aoeStats.royalGhostAOE,
        attackSpeed: 1800,
        initHitSpeed: 600,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        invisTime: 1800,
        spawnInvis: true,
        canJumpRiver: true
    },
    princess: {
        name: 'Princess',
        symbol: '🎉',
        cost: 3,
        hp: 261,
        projectileStats: projectileStats.princessArrows,
        attackSpeed: 3000,
        initHitSpeed: 300,
        range: 216,
        viewRange: 9.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    babyDragon: {
        name: 'Baby Dragon',
        symbol: '🐉',
        cost: 4,
        hp: 1152,
        projectileStats: projectileStats.babyDragonFire,
        attackSpeed: 1500,
        initHitSpeed: 300,
        range: 84,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    darkPrince: {
        name: 'Dark Prince',
        symbol: '🪻',
        imgPath: '../Imgs/Sprites/Dark_Prince.png',
        cost: 4,
        hp: 1200,
        sheildHP: 240,
        aoeStats: aoeStats.darkPrinceAOE,
        chargeAOEStats: aoeStats.darkPrinceAOE,
        chargeSpeed: 120,
        chargeTriggerDistance: 72,
        attackSpeed: 1300,
        initHitSpeed: 400,
        range: 1.2 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    berserker: {
        name: 'Berserker',
        symbol: '👧',
        cost: 2,
        hp: 896,
        damage: 102,
        attackSpeed: 600,
        initHitSpeed: 200,
        range: 0.8 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 15,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    miner: {
        name: 'Miner',
        symbol: '🪏',
        cost: 3,
        type: 'spell',
        damage: 0,
        distance: 9999,
        size: 2,
        speed: 200,
        colour: '#b16800ff',
        lifetime: 9999,
        deathSpawnStats: otherUnits.miner,
        deathSpawnNum: 1,
        particle: particleStats.dirt,
        particleSpread: 15,
        particleCount: 1,
        particleSpeed: 250
    },
    battleRam: {
        name: 'Battle Ram',
        symbol: '🐏',
        cost: 4,
        hp: 967,
        damage: 286,
        deathSpawnNum: 2,
        deathSpawnStats: otherUnits.barbarian,
        chargeDamage: 573,
        chargeSpeed: 120,
        chargeTriggerDistance: 72,
        attackSpeed: 9999,
        range: 21,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        dieOnAttack: true
    },
    bomber: {
        name: 'Bomber',
        symbol: '💣',
        cost: 2,
        hp: 304,
        projectileStats: projectileStats.bomberBomb,
        attackSpeed: 1800,
        initHitSpeed: 200,
        range: 108,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    royalHogs: {
        name: 'Royal Hogs',
        symbol: '🐷',
        cost: 5,
        hp: 837,
        damage: 74,
        attackSpeed: 1200,
        initHitSpeed: 400,
        range: 24,
        viewRange: 9.5 * game.gridSize,
        size: 16,
        speed: 120,
        count: 4,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit'
    },
    eWizard: {
        name: 'Electro Wizard',
        symbol: '🔌',
        cost: 4,
        hp: 714,
        projectileStats: projectileStats.eWizardLightning,
        attackSpeed: 1800,
        initHitSpeed: 600,
        range: 5 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        spawnAOEStats: aoeStats.eWizardSpawnAOE
    },
    goblinGang: {
        name: 'Goblin Gang',
        cost: 3,
        symbol: '🤢👺'
    },
    barbarianBarrel: {
        name: 'Barbarian Barrel',
        symbol: '🛢️',
        cost: 2,
        type: 'unit',
        pierce: 9999,
        width: 2.6 * game.gridSize,
        height: 36,
        damage: 240,
        distance: 4.5 * game.gridSize,
        targetPriority: 'ground',
        speed: 100,
        colour: '#b16800ff',
        lifetime: 99999,
        deathSpawnStats: otherUnits.barbarian
    },
    motherWitch: {
        name: 'Mother Witch',
        symbol: '🧙‍♀️',
        cost: 4,
        hp: 529,
        projectileStats: projectileStats.motherWitchBullet,
        attackSpeed: 900,
        initHitSpeed: 300,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    battleHealer: {
        name: 'Battle Healer',
        symbol: '❤️‍🩹',
        cost: 4,
        hp: 1717,
        damage: 148,
        attackAOE: aoeStats.battleHealerAOE,
        attackSpeed: 1500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        spawnAOEStats: aoeStats.battleHealerSpawnAOE
    },
    wizard: {
        name: 'Wizard',
        symbol: '🪄',
        cost: 5,
        hp: 755,
        projectileStats: projectileStats.wizardFireball,
        attackSpeed: 1400,
        initHitSpeed: 400,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    mortar: {
        name: 'Mortar',
        symbol: '🪨',
        cost: 4,
        hp: 1369,
        projectileStats: projectileStats.mortarRock,
        attackSpeed: 5000,
        initHitSpeed: 1000,
        range: {min: 84, max: 276},
        viewRange: {min: 84, max: 276},
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 3500,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 45.6
    },
    tesla: {
        name: 'Tesla',
        symbol: '🧂',
        cost: 4,
        hp: 1152,
        projectileStats: projectileStats.teslaLightning,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 5.5 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: game.gridSize,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'building',
        hpLostPerSecond: 38.4,
        canHide: true
    },
    skeletonBarrel: {
        name: 'Skeleton Barrel',
        symbol: '🛢️',
        cost: 3,
        hp: 532,
        damage: 312,
        deathAOEStats: aoeStats.golemDeathAOE,
        deathSpawnNum: 7,
        deathSpawnStats: otherUnits.skeleton,
        attackSpeed: 2500,
        range: 20,
        viewRange: 7.7 * game.gridSize,
        size: 18,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'flying',
        dieOnAttack: true
    },
    eGiant: {
        name: 'Electro Giant',
        symbol: '💪🏿',
        imgPath: '../Imgs/Sprites/Electro_Giant.png',
        cost: 7,
        hp: 3855,
        damage: 163,
        reflectedStats: projectileStats.eGiantZap,
        reflectionRadius: 72,
        attackSpeed: 2100,
        initHitSpeed: 1500,
        range: 1.2 * game.gridSize,
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings', 
        type: 'unit'
    },
    healSpirit: {
        name: 'Heal Spirit',
        symbol: '✚',
        cost: 1,
        hp: 230,
        projectileStats: projectileStats.healSpirit,
        attackSpeed: 2000,
        range: 60,
        viewRange: 5.5 * game.gridSize,
        size: 12,
        speed: 120,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        dieOnAttack: true
    },
    iceWizard: {
        name: 'Ice Wizard',
        symbol: '🥶',
        cost: 3,
        hp: 688,
        projectileStats: projectileStats.iceWizardBullet,
        attackSpeed: 1700,
        initHitSpeed: 500,
        range: 132,
        viewRange: 5.5 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        spawnAOEStats: aoeStats.iceWizardSpawnAOE
    },
    firecracker: {
        name: 'Firecracker',
        symbol: '🎉',
        cost: 3,
        hp: 304,
        projectileStats: projectileStats.firecrackerBullet,
        attackSpeed: 3000,
        initHitSpeed: 650,
        range: 6 * game.gridSize,
        viewRange: 8.5 * game.gridSize,
        size: 18,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
        recoil: 4
    },
    suspiciousBush: {
        name: 'Suspicious Bush',
        symbol: '🌳',
        cost: 2,
        hp: 81,
        damage: 0,
        deathSpawnNum: 2,
        deathSpawnStats: otherUnits.bushGoblin,
        attackSpeed: 2000,
        range: 25,
        viewRange: 5.5,
        size: 22,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        invisTime: 1,
        spawnInvis: true,
        dieOnAttack: true
    },
    tombstone: {
        name: 'Tombstone',
        symbol: '🪦',
        cost: 3,
        hp: 529,
        damage: 0,
        supportSpawnNum: 2,
        supportSpawnSpeed: 3500,
        supportStats: otherUnits.skeleton,
        deathSpawnNum: 4,
        deathSpawnStats: otherUnits.skeleton,
        range: game.gridSize * 1.1,
        viewRange: game.gridSize * 1.1,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 17.6
    },
    flyingMachine: {
        name: 'Flying Machine',
        symbol: '🚁',
        cost: 4,
        hp: 614,
        projectileStats: projectileStats.flyingMachineBullet,
        attackSpeed: 1100,
        initHitSpeed: 500,
        range: 6 * game.gridSize,
        viewRange: 6 * game.gridSize,
        size: 20,
        speed: 90,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    zappies: {
        name: 'Zappies',
        symbol: '🔋',
        cost: 4,
        hp: 529,
        projectileStats: projectileStats.zappiesZap,
        attackSpeed: 2100,
        initHitSpeed: 800,
        range: 4.5 * game.gridSize,
        viewRange: 5 * game.gridSize,
        size: 18,
        speed: 60,
        count: 3,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit',
    },
    furnace: {
        name: 'Furnace',
        symbol: '🏭',
        cost: 4,
        hp: 727,
        projectileStats: projectileStats.furncaceBullet,
        supportSpawnNum: 1,
        supportSpawnSpeed: 7000,
        supportStats: otherUnits.fireSpirit,
        attackSpeed: 1100,
        range: 5.5 * game.gridSize,
        viewRange: 6 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    threeMusketeers: {
        name: 'Three Musketees',
        symbol: '🔫',
        displaySymbol: '🔫🔫',
        cost: 9,
        hp: 721,
        projectileStats: projectileStats.musketeerBullet,
        attackSpeed: 1000,
        initHitSpeed: 700,
        range: 140,
        viewRange: 6 * game.gridSize,
        size: 18,
        speed: 60,
        deployTime: 1000,
        count: 3,
        targetPriority: 'all',
        type: 'unit'
    },
    nightWitch: {
        name: 'Night Witch',
        symbol: '🧛🏿',
        cost: 4,
        hp: 906,
        damage: 286,
        supportSpawnNum: 2,
        supportSpawnSpeed: 5000,
        supportStats: otherUnits.bat,
        attackSpeed: 1300,
        initHitSpeed: 750,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    royalDelivery: {
        name: 'Royal Delivery',
        symbol: '🪣',
        displaySymbol: '📦',
        imgPath: '../Imgs/Sprites/Royal_Recruit.png',
        displayImgPath: '../Imgs/Sprites/Royal_Delivery.png',
        cost: 3,
        hp: 547,
        sheildHP: 240,
        damage: 133,
        attackSpeed: 1300,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 19,
        speed: 60,
        targetPriority: 'ground',
        type: 'unit',
        spawnAOEStats: aoeStats.royalDeliveryAOE,
        spawnDelay: 3000
    },
    barbHut: {
        name: 'Barbarian Hut',
        symbol: '🏠',
        cost: 6,
        hp: 1164,
        damage: 0,
        supportSpawnNum: 3,
        supportSpawnSpeed: 15000,
        initSupportSpawnSpeed: 200,
        supportStats: otherUnits.barbarian,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.barbarian,
        range: game.gridSize * 1.1,
        viewRange: game.gridSize * 1.1,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 38.8
    },
    goblinHut: {
        name: 'Goblin Hut',
        symbol: '🛖',
        cost: 4,
        hp: 1228,
        damage: 0,
        supportSpawnNum: 1,
        supportSpawnSpeed: 1900,
        supportStats: otherUnits.spearGoblin,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.spearGoblin,
        range: 144,
        viewRange: 6 * game.gridSize,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'building',
        hpLostPerSecond: 40.9,
        spawnInRange: true
    },
    rascals: {
        name: 'Rascals',
        cost: 5,
        symbol: '👨🏻👩🏻'
    },
    elixirGolem: {
        name: 'Elixir Golem',
        symbol: '⏺',
        imgPath: '../Imgs/Sprites/Elixir_Golem.png',
        cost: 3,
        hp: 1569,
        damage: 253,
        deathSpawnNum: 2,
        deathSpawnStats: otherUnits.elixirGolemite,
        attackSpeed: 1100,
        initHitSpeed: 800,
        range: 23,
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        deathEnemyElixir: 1
    },
    giantSkeleton: {
        name: 'Giant Skeleton',
        symbol: '☠️',
        cost: 6,
        hp: 3617,
        damage: 266,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.giantSkeletonBomb,
        attackSpeed: 1400,
        initHitSpeed: 300,
        range: 25,
        viewRange: 5 * game.gridSize,
        size: 23,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit'
    },
    sparky: {
        name: 'sparky',
        symbol: '🪫',
        cost: 6,
        hp: 1451,
        projectileStats: projectileStats.sparkyBullet,
        attackSpeed: 4000,
        initHitSpeed: 1000,
        range: 120,
        viewRange: 5 * game.gridSize,
        size: 20,
        speed: 45,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        chargeAttack: true,
        recoil: 4
    },
    goblinDemolisher: {
        name: 'Goblin Demolisher',
        symbol: '🧨',
        cost: 4,
        hp: 1300,
        projectileStats: projectileStats.goblinDemolisherBomb,
        attackSpeed: 1200,
        initHitSpeed: 500,
        range: 120,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        activatedStats: otherUnits.kamikazeGoblin,
        activationHP: 0.5
    },
    cannonCart: {
        name: 'Cannon Cart',
        symbol: '🛒',
        cost: 5,
        hp: 1809,
        projectileStats: projectileStats.cannonCartBullet,
        attackSpeed: 900,
        initHitSpeed: 500,
        range: 132,
        viewRange: 6 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        activatedStats: otherUnits.brokenCannonCart,
        activationHP: 0.5
    },
    phoenix: {
        name: 'Phoenix',
        symbol: '🐦‍🔥',
        cost: 4,
        hp: 1052,
        damage: 217,
        deathSpawnNum: 1,
        deathSpawnStats: otherUnits.phoenixEgg,
        deathAOEStats: aoeStats.phoenixDeathAOE,
        attackSpeed: 1000,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'flying'
    },
    elixirCollector: {
        name: 'Elixir Collector',
        symbol: '🏦',
        cost: 6,
        hp: 1070,
        attackSpeed: 1000,
        initHitSpeed: 1000,
        range: game.gridSize * 1.1,
        viewRange: game.gridSize * 1.1,
        size: game.gridSize * 1.1,
        speed: 0,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'building',
        hpLostPerSecond: 12.4,
        elixirSpeed: 12000,
        elixirAmount: 1,
        deathElixir: 1
    },
    goblinDrill: {
        name: 'Goblin Drill',
        symbol: '🛠️',
        cost: 4,
        type: 'spell',
        damage: 0,
        distance: 9999,
        size: 2,
        speed: 200,
        colour: '#b16800ff',
        lifetime: 9999,
        deathSpawnStats: otherUnits.goblinDrill,
        deathSpawnNum: 1,
        particle: particleStats.dirt,
        particleSpread: 15,
        particleCount: 1,
        particleSpeed: 250
    },
    executioner: {
        name: 'Executioner',
        symbol: '⛏️',
        cost: 5,
        hp: 1280,
        projectileStats: projectileStats.executionerAxe,
        attackSpeed: 2400,
        initHitSpeed: 500,
        range: 4.5 * game.gridSize,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    hunter: {
        name: 'Hunter',
        symbol: '🍗',
        cost: 4,
        hp: 885,
        projectileStats: projectileStats.hunterBullet,
        projectileCount: 10,
        projectileSpread: Math.PI / 6,
        attackSpeed: 2200,
        initHitSpeed: 700,
        range: 96,
        viewRange: 5.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'all',
        type: 'unit'
    },
    goblinGiant: {
        name: 'Goblin Giant',
        symbol: '🧌',
        cost: 6,
        hp: 3022,
        damage: 176,
        attackSpeed: 1500,
        initHitSpeed: 800,
        range: 1.6 * game.gridSize,
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        backUnitNum: 2,
        backUnitStats: otherUnits.spearGoblin,
        deathSpawnNum: 2,
        deathSpawnStats: otherUnits.spearGoblin
    },
    ramRider: {
        name: 'Ram Rider',
        symbol: '🐏',
        cost: 5,
        hp: 1697,
        damage: 250,
        chargeDamage: 501,
        chargeSpeed: 120,
        chargeTriggerDistance: 48,
        attackSpeed: 1800,
        initHitSpeed: 600,
        range: 22,
        viewRange: 7.5 * game.gridSize,
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        backUnitNum: 1,
        backUnitStats: otherUnits.ramRider
    },
    runeGiant: {
        name: 'Rune Giant',
        symbol: '🔨',
        cost: 4,
        hp: 2662,
        damage: 120,
        attackSpeed: 1500,
        initHitSpeed: 500,
        range: 1.6 * game.gridSize,
        viewRange: 7.5 * game.gridSize,
        size: 22,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'buildings',
        type: 'unit',
        enchantCount: 2,
        enchantDurationAfterDeath: 5000,
        enchantRange: 8.5 * game.gridSize
    },
    /*fisherman: {
        name: 'Fisherman',
        symbol: '⚓️',
        cost: 3,
        hp: 870,
        damage: 194,
        attackSpeed: 1300,
        initHitSpeed: 100,
        range: 1.2 * game.gridSize,
        viewRange: 7 * game.gridSize,
        hookRange: {min: 3.5 * game.gridSize, max: 7 * game.gridSize},
        size: 20,
        speed: 60,
        deployTime: 1000,
        targetPriority: 'ground',
        type: 'unit',
        hookProjectileStats: projectileStats.fishermanHook
    },*/
    mirror: {
        name: 'Mirror',
        symbol: '🪞',
        cost: '?'
    }
};

const towers = {
    princess: {
        name: 'princess',
        symbol: '👸',
        hp: 3052,
        projectileStats: projectileStats.princessTowerArrow,
        attackSpeed: 800,
        range: 7.5 * game.gridSize,
        size: 36,
        type: 'building'
    },
    king: {
        name: 'king',
        symbol: '👑',
        hp: 4824,
        projectileStats: projectileStats.kingTowerBullet,
        attackSpeed: 1000,
        range: 7 * game.gridSize,
        size: 48,
        type: 'building'
    }
};